#!/usr/bin/env python3
"""
Build the Passport flag asset: one sprite sheet (public/flags.png) + CSS (public/flags.css).

Source: flagcdn.com flat PNG flags, keyed by ISO 3166-1 alpha-2 (lowercase) — free, no API key.
Self-hosted on purpose (the game embeds all assets; no external CDN at runtime — privacy/CSP posture).

Output contract (the client + server depend on this — do not change names):
  - public/flags.png : a single-column sprite, one CELL (CELL_W x CELL_H) per country, in `codes` order.
  - public/flags.css : `.flag` base class + `.flag-<iso>` background-position per country.
        <span class="flag flag-fr" title="France"></span>  ->  24x18 French flag, name on hover.

Re-run any time:  python scripts/build_flags.py
Network required (downloads ~260 tiny PNGs). Output is COUNTS ONLY (no binary, no country list).
"""
import io, json, os, sys, urllib.request, concurrent.futures as cf
from PIL import Image

CELL_W, CELL_H = 24, 18                       # on-disk + on-screen cell size (flat, crisp)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PNG = os.path.join(ROOT, "public", "flags.png")
OUT_CSS = os.path.join(ROOT, "public", "flags.css")
UA = {"User-Agent": "Mozilla/5.0 (flag-sprite-builder)"}

def fetch(url, timeout=20):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read()

# Canonical ISO 3166-1 alpha-2 set (+ xk Kosovo, which flagcdn serves). Codes the source lacks a
# flag for are simply skipped at download time, so an over-broad list is harmless.
ISO_A2 = (
    "ad ae af ag ai al am ao aq ar as at au aw ax az ba bb bd be bf bg bh bi bj bl bm bn bo bq br "
    "bs bt bv bw by bz ca cc cd cf cg ch ci ck cl cm cn co cr cu cv cw cx cy cz de dj dk dm do dz "
    "ec ee eg eh er es et fi fj fk fm fo fr ga gb gd ge gf gg gh gi gl gm gn gp gq gr gs gt gu gw "
    "gy hk hm hn hr ht hu id ie il im in io iq ir is it je jm jo jp ke kg kh ki km kn kp kr kw ky "
    "kz la lb lc li lk lr ls lt lu lv ly ma mc md me mf mg mh mk ml mm mn mo mp mq mr ms mt mu mv "
    "mw mx my mz na nc ne nf ng ni nl no np nr nu nz om pa pe pf pg ph pk pl pm pn pr ps pt pw py "
    "qa re ro rs ru rw sa sb sc sd se sg sh si sj sk sl sm sn so sr ss st sv sx sy sz tc td tf tg "
    "th tj tk tl tm tn to tr tt tv tw tz ua ug um us uy uz va vc ve vg vi vn vu wf ws xk ye yt za "
    "zm zw"
).split()

def main():
    codes = sorted(set(ISO_A2))

    def grab(code):
        try:
            data = fetch(f"https://flagcdn.com/w40/{code}.png")
            im = Image.open(io.BytesIO(data)).convert("RGBA")
            im.thumbnail((CELL_W, CELL_H), Image.LANCZOS)     # fit inside the cell, keep aspect
            cell = Image.new("RGBA", (CELL_W, CELL_H), (0, 0, 0, 0))
            cell.paste(im, ((CELL_W - im.width) // 2, (CELL_H - im.height) // 2))
            return code, cell
        except Exception:
            return code, None

    cells = {}
    with cf.ThreadPoolExecutor(max_workers=16) as ex:
        for code, cell in ex.map(grab, codes):
            if cell is not None:
                cells[code] = cell

    have = [c for c in codes if c in cells]                  # keep stable ordering
    if not have:
        print("ERROR: downloaded 0 flags (network?)", file=sys.stderr)
        sys.exit(1)

    sheet = Image.new("RGBA", (CELL_W, CELL_H * len(have)), (0, 0, 0, 0))
    for i, code in enumerate(have):
        sheet.paste(cells[code], (0, i * CELL_H))
    os.makedirs(os.path.dirname(OUT_PNG), exist_ok=True)
    sheet.save(OUT_PNG, optimize=True)

    css = [
        "/* Generated by scripts/build_flags.py — flat country flags (flagcdn, ISO-3166 a2). */",
        ".flag{display:inline-block;width:%dpx;height:%dpx;background-image:url('/flags.png');"
        "background-repeat:no-repeat;background-size:%dpx %dpx;vertical-align:middle;"
        "box-shadow:0 0 0 1px rgba(0,0,0,.25);image-rendering:auto}" % (
            CELL_W, CELL_H, CELL_W, CELL_H * len(have)),
    ]
    for i, code in enumerate(have):
        css.append(".flag-%s{background-position:0 -%dpx}" % (code, i * CELL_H))
    with open(OUT_CSS, "w", encoding="utf-8") as f:
        f.write("\n".join(css) + "\n")

    png_kb = os.path.getsize(OUT_PNG) / 1024.0
    print("flags: %d/%d  sprite=%dx%d  png=%.1fKB  css=%s" % (
        len(have), len(codes), CELL_W, CELL_H * len(have), png_kb, OUT_CSS))

if __name__ == "__main__":
    main()
